name: CI/CD Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check for Git
        run: |
          if ! command -v git &> /dev/null
          then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
          else
              echo "Git is already installed."
          fi

      - name: Check for Docker
        run: |
          if ! command -v docker &> /dev/null
          then
              echo "Docker not found, installing..."
              sudo apt-get update
              sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common && \
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
                sudo apt-get update && \
                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          else
              echo "Docker is already installed."
          fi

      - name: Check for Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null
          then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          else
              echo "Docker Compose is already installed."
          fi

      - name: Check for Maven
        run: |
          if ! command -v mvn &> /dev/null
          then
              echo "Maven not found, installing..."
              sudo apt-get update
              sudo apt-get install -y maven
          else
              echo "Maven is already installed."
          fi

      - name: Validate Installation
        run: |
          echo "Validating installation..."
          command -v git
          command -v docker
          command -v docker-compose
          command -v mvn

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: ./mvnw -B package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify JAR file
        run: |
          echo "Verifying JAR file presence..."
          ls -al target/
          if [ ! -f target/*.jar ]; then
            echo "JAR file not found in target directory!"
            exit 1
          fi

      - name: Deploy application
        env:
          DEPLOY_SERVER: '103.151.111.202' 
          DEPLOY_PORT: '8080'
          DEPLOY_USER: 'deploy'
        run: |
          echo "Deploying application to $DEPLOY_SERVER"
          scp -i /path/to/your/private/key target/*.jar $DEPLOY_USER@$DEPLOY_SERVER:/path/to/deploy/
          ssh -i /path/to/your/private/key $DEPLOY_USER@$DEPLOY_SERVER "java -jar /path/to/deploy/*.jar"

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check application URL
        run: |
          echo "Checking application URL"
          curl -s http://103.151.111.202:8080 || exit 1

      - name: Run tests
        run: ./mvnw test
