# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   setup: 
    runs-on: self-hosted
    steps:
      - name: Check for Git
        run: |
          if ! command -v git &> /dev/null
          then
              echo "Git not found, installing..." 
              sudo apt-get update
              sudo apt-get install -y git
          else
              echo "Git is already installed."
          fi

      - name: Check for Docker
        run: |
          if ! command -v docker &> /dev/null
          then
              echo "Docker not found, installing..."
              sudo apt-get update
              sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common && \
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
                sudo apt-get update && \
                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          else
              echo "Docker is already installed."
          fi

      - name: Check for Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null
          then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          else
              echo "Docker Compose is already installed."
          fi

      - name: Check for Maven
        run: |
          if ! command -v mvn &> /dev/null
          then
              echo "Maven not found, installing..."
              sudo apt-get update
              sudo apt-get install -y maven
          else
              echo "Maven is already installed."
          fi

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build with Maven
        run: ./mvnw -B package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy application
        env:
          DEPLOY_SERVER: '103.151.111.202'
          DEPLOY_PORT: '8080'
          DEPLOY_USER: 'deploy'
        run: |
          echo "Deploying to $DEPLOY_SERVER on port $DEPLOY_PORT"
          scp -r target/*.jar $DEPLOY_USER@$DEPLOY_SERVER:/path/to/deployment/
          ssh $DEPLOY_USER@$DEPLOY_SERVER "pkill -f 'java -jar target/*.jar' || true"
          ssh $DEPLOY_USER@$DEPLOY_SERVER "nohup java -jar /path/to/deployment/*.jar > /dev/null 2>&1 &"

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test application
        run: |
          curl -s http://103.151.111.202:8080 || exit 1

